version: '2'

networks:
  app-tier:
    driver: bridge

services:
  rabbitmq:
    container_name: 'shop-rabbit'
    image: 'bitnami/rabbitmq:latest'
    networks:
      - app-tier
    environment:
      - RABBITMQ_USERNAME=shop
      - RABBITMQ_PASSWORD=shop

  myapp:
    image: 'rabbitmq'
    networks:
      - app-tier
